apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    password: juniper
    user: juniper
    database: juniper
    basicAuth: false
    basicAuthUser: 
    basicAuthPassword: 
    withCredentials: 
    isDefault: true
    editable: true

